terraform {
  required_version = ">= 1.11.0" # S3-native state locking (use_lockfile)

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 6.0"
    }
    random = {
      source  = "hashicorp/random"
      version = "~> 3.0"
    }
  }

  # Partial backend — concrete settings come from backend.hcl (generated by bootstrap):
  #   terraform -chdir=terraform/environments/dev init -backend-config=backend.hcl
  backend "s3" {}
}
