#!/usr/bin/env node
// docs-sync.mjs -- render the project brain's source of truth (s2d/ and
// tracking/) into VitePress pages under docs/. Single source of truth stays in
// s2d/ and tracking/; this script copies content into docs/ with a small
// generated frontmatter header so the doc site always reflects reality.
//
// Prose is normalized to the ASCII house style on the way in (shared with
// context-ingest.mjs) so pages derived from verbatim artifacts or knowledge
// notes still pass prose-lint. Normalization is idempotent.
//
// Only node built-ins plus the local prose normalizer are imported.
//
// Power-of-10 in spirit: every loop is bounded by a constant cap, fs return
// values are checked, functions are small and named, and inputs are asserted
// before use.

import { existsSync, mkdirSync, readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs'
import { dirname, join, relative } from 'node:path'
import { fileURLToPath } from 'node:url'
import { normalizeProse } from './lib/normalize-prose.mjs'

// Hard caps so no loop can run unbounded.
const MAX_FILES = 2000
const MAX_DEPTH = 8

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url))
const ROOT = join(SCRIPT_DIR, '..')
const DOCS = join(ROOT, 'docs')

// Each rule maps a source path in the brain to a destination page under docs/.
// `kind` is "file" for a single page or "tree" for a directory of pages.
const RULES = [
  { kind: 'file', src: 's2d/overview.md', dst: 'overview.md', title: 'Project Overview' },
  { kind: 'file', src: 's2d/story.md', dst: 'story.md', title: 'The Story' },
  { kind: 'file', src: 's2d/scribl-full-app-spec.md', dst: 'scribl-full-app-spec.md', title: 'Full-App Spec' },
  { kind: 'file', src: 's2d/android-distribution.md', dst: 'android-distribution.md', title: 'Android Distribution' },
  { kind: 'file', src: 's2d/ios-distribution.md', dst: 'ios-distribution.md', title: 'iOS Distribution' },
  { kind: 'file', src: 's2d/status.md', dst: 'status.md', title: 'Status' },
  { kind: 'file', src: 's2d/sow-mobile-app-development-extract.md', dst: 'sow-mobile-app-development-extract.md', title: 'SOW Extract: Mobile App Development' },
  { kind: 'tree', src: 's2d/handbook', dst: 'handbook', title: 'Handbook' },
  { kind: 'file', src: 's2d/input-artifacts.md', dst: 'input-artifacts.md', title: 'Input Artifacts' },
  { kind: 'tree', src: 's2d/context', dst: 'context', title: 'Project Information' },
  { kind: 'file', src: 'tracking/board.md', dst: 'board.md', title: 'Board' },
  { kind: 'file', src: 'tracking/roadmap.md', dst: 'roadmap.md', title: 'Roadmap' },
  { kind: 'tree', src: 'tracking/stories', dst: 'stories', title: 'Stories' },
  { kind: 'file', src: 'tracking/production-backlog.md', dst: 'production-backlog.md', title: 'Production Starter Backlog' },
  { kind: 'file', src: 'tracking/expo-rebuild-epics.md', dst: 'expo-rebuild-epics.md', title: 'Expo Rebuild Epics' },
  { kind: 'file', src: 'tracking/production-sprint-backlog.md', dst: 'production-sprint-backlog.md', title: 'Production Sprint Backlog' },
  { kind: 'file', src: 'tracking/jira-board.md', dst: 'jira-board.md', title: 'Jira Board (CMPSR)' },
  { kind: 'file', src: 's2d/production-backend-plan.md', dst: 'production-backend-plan.md', title: 'Production Backend Plan' },
  { kind: 'file', src: 's2d/future-scale-track.md', dst: 'future-scale-track.md', title: 'Future Scale Track' },
  { kind: 'tree', src: 'reviews', dst: 'reviews', title: 'Reviews' },
  { kind: 'tree', src: 'knowledge', dst: 'knowledge', title: 'Knowledge' }
]

// Assert a precondition; fail loud rather than producing a broken site.
function assert(cond, message) {
  if (!cond) {
    throw new Error(`docs-sync: ${message}`)
  }
}

// Build the generated frontmatter header prepended to every synced page. The
// provenance notice is an HTML comment so it never renders as body text; the
// "do not hand-edit" warning still shows to anyone viewing the page source.
function header(title, sourceRel) {
  assert(typeof title === 'string' && title.length > 0, 'header needs a title')
  assert(typeof sourceRel === 'string' && sourceRel.length > 0, 'header needs a source')
  // Quote the title: synced titles can contain a colon (for example
  // "Stories: S-001-..."), which is not valid bare YAML.
  const safeTitle = title.replace(/"/g, '\\"')
  const lines = [
    '---',
    `title: "${safeTitle}"`,
    '---',
    '',
    `<!-- Generated by docs-sync from \`${sourceRel}\`. Do not hand-edit; edit the`,
    '     source and re-run `npm run docs:sync`. -->',
    '',
    ''
  ]
  return lines.join('\n')
}

// Ensure a directory exists; returns true if present after the call.
function ensureDir(dir) {
  assert(typeof dir === 'string' && dir.length > 0, 'ensureDir needs a path')
  if (!existsSync(dir)) {
    mkdirSync(dir, { recursive: true })
  }
  return existsSync(dir)
}

// List markdown files under a directory, bounded by MAX_FILES and MAX_DEPTH.
function collectMarkdown(dir) {
  assert(typeof dir === 'string', 'collectMarkdown needs a path')
  const found = []
  // Explicit stack with depth so recursion stays bounded and traceable.
  const stack = [{ path: dir, depth: 0 }]
  let guard = 0
  while (stack.length > 0 && guard < MAX_FILES) {
    guard += 1
    const node = stack.pop()
    if (node.depth > MAX_DEPTH) {
      continue
    }
    const entries = readdirSync(node.path, { withFileTypes: true })
    for (let i = 0; i < entries.length && found.length < MAX_FILES; i += 1) {
      const entry = entries[i]
      const full = join(node.path, entry.name)
      if (entry.isDirectory()) {
        stack.push({ path: full, depth: node.depth + 1 })
      } else if (entry.isFile() && entry.name.endsWith('.md')) {
        found.push(full)
      }
    }
  }
  assert(guard < MAX_FILES, 'collectMarkdown hit the file cap; raise MAX_FILES or split the tree')
  return found
}

// Copy one source file to one destination page, prepending the header.
function syncFile(srcAbs, dstAbs, title) {
  assert(existsSync(srcAbs), `source missing: ${srcAbs}`)
  const ok = ensureDir(dirname(dstAbs))
  assert(ok, `could not create directory for ${dstAbs}`)
  const body = readFileSync(srcAbs, 'utf8')
  const sourceRel = relative(ROOT, srcAbs)
  writeFileSync(dstAbs, header(title, sourceRel) + normalizeProse(body), 'utf8')
  assert(existsSync(dstAbs), `write failed: ${dstAbs}`)
  return dstAbs
}

// Sync a directory of markdown into a docs/ subtree. If the source tree already
// carries its own index.md (an authored or generated landing page), it is
// rendered as-is and the auto-generated link index is skipped, so a curated
// landing is never clobbered. Otherwise a plain link index is written.
function syncTree(srcAbs, dstDirAbs, title) {
  const files = collectMarkdown(srcAbs)
  const written = []
  const indexLinks = []
  let hasSourceIndex = false
  for (let i = 0; i < files.length && i < MAX_FILES; i += 1) {
    const file = files[i]
    const rel = relative(srcAbs, file)
    const dstAbs = join(dstDirAbs, rel)
    if (rel === 'index.md') {
      hasSourceIndex = true
      syncFile(file, dstAbs, title)
      written.push(dstAbs)
      continue
    }
    syncFile(file, dstAbs, `${title}: ${rel.replace(/\.md$/, '')}`)
    written.push(dstAbs)
    indexLinks.push(`- [${rel.replace(/\.md$/, '')}](./${rel.replace(/\.md$/, '')})`)
  }
  if (!hasSourceIndex) {
    writeIndex(dstDirAbs, title, indexLinks)
  }
  return written
}

// Write an index.md listing the synced pages in a tree.
function writeIndex(dstDirAbs, title, links) {
  const ok = ensureDir(dstDirAbs)
  assert(ok, `could not create directory ${dstDirAbs}`)
  const body = links.length > 0 ? links.join('\n') + '\n' : '_No pages yet._\n'
  const indexPath = join(dstDirAbs, 'index.md')
  writeFileSync(indexPath, header(title, relative(ROOT, dstDirAbs)) + body, 'utf8')
  assert(existsSync(indexPath), `index write failed: ${indexPath}`)
}

// Apply one rule; skip gracefully if its source does not exist yet.
function applyRule(rule) {
  assert(rule && rule.kind && rule.src && rule.dst, 'malformed rule')
  const srcAbs = join(ROOT, rule.src)
  if (!existsSync(srcAbs)) {
    process.stdout.write(`docs-sync: skip (no source) ${rule.src}\n`)
    return 0
  }
  if (rule.kind === 'file') {
    assert(statSync(srcAbs).isFile(), `expected a file: ${rule.src}`)
    syncFile(srcAbs, join(DOCS, rule.dst), rule.title)
    return 1
  }
  assert(statSync(srcAbs).isDirectory(), `expected a directory: ${rule.src}`)
  const written = syncTree(srcAbs, join(DOCS, rule.dst), rule.title)
  return written.length
}

function main() {
  assert(existsSync(ROOT), 'brain root not found')
  const ok = ensureDir(DOCS)
  assert(ok, 'docs/ directory could not be created')
  let total = 0
  for (let i = 0; i < RULES.length && i < MAX_FILES; i += 1) {
    total += applyRule(RULES[i])
  }
  process.stdout.write(`docs-sync: synced ${total} page(s)\n`)
}

main()
